### ISSUE TITLE
resevoir loses stored fluids

### ISSUE THREAD

**Issue by torterra2234** [RootsTeam/Embers#165]
minecraft 1.11.2, forge 13.20.0.2282, embers 0.206

on occasion exiting the game and re-entering purges the fluid stored in the reservoir (or at least in the caminite rings), currently happening with lava, just in case its specific to a given liquid

**Comment by elucent** [comment]
Should be fixed for the next update.

**Comment by Terpo** [comment]
Just want to imform you that the bug is still a thing. Hanging on 1.11.2 with forge 2304 and embers 0.214 (release 27th may)

**Comment by elucent** [comment]
Any way you can replicate it?

**Comment by Terpo** [comment]
Yeah, everytime I log back into the server my reservoir is empty again. I added another tank as buffer behind it for now.
