### ISSUE TITLE
Ore Spawn

### ISSUE THREAD

**Issue by phit** [RootsTeam/Embers#189]
Not sure why but apparently none of the ember ores spawn in any other dimension than the overworld, using your compat ores for a modpack and neither the Aroma Mining dimension nor the Extra Utilities Deep Dark have your ores spawning. 

embers-0.212

**Comment by phit** [comment]
Ah I see you are specifically checking for dimension ID 0, could you instead consider something like this

```java
    int dimension = world.provider.getDimension();
    if (dimension != -1 && dimension != 1) {
        dospawnstuff
    }

```

most other mods are doing their worldgen like that or add a config option.

**Comment by elucent** [comment]
I don't do that anymore. Should be fixed in at least 0.213.

And you should never make a pull request for less than one line of code. :P

**Comment by phit** [comment]
Checking for world type overworld doesn't fix the issue, since the Deep Dark has a different world type.
Could we please get a config for this?

**Comment by elucent** [comment]
Well...that's odd. Just blacklisting the nether and end doesn't make sense -- what about mods that add drastically different dimensions just like the nether and end?

I could probably change it to that, but lemme think on it first. Reopening.

**Comment by phit** [comment]
Here's a few options I came up with, either block nether and end like [actually additions](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/gen/OreGen.java#L60), hardcode certain well known dimension mods or add a config blacklist/whitelist for either world id or world type that defaults to just overworld. Personally i prefer the last option, since this oregen feature seems to be focused on giving pack authors the ability to use your ores for everything and pack authors like being able to chose.

**Comment by elucent** [comment]
I'll add a blacklist.

**Comment by elucent** [comment]
Blacklist added. Finally got back to Embers, will release a final bugfixed 1.11 version soon!
